// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250723065147_TestRemoveRoles")]
    partial class TestRemoveRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.Property<int>("GenresId")
                        .HasColumnType("integer");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.HasKey("GenresId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieGenres", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ReservationSeat", b =>
                {
                    b.Property<int>("ReservationId")
                        .HasColumnType("integer");

                    b.Property<int>("SeatsId")
                        .HasColumnType("integer");

                    b.HasKey("ReservationId", "SeatsId");

                    b.HasIndex("SeatsId");

                    b.ToTable("ReservationSeats", (string)null);
                });

            modelBuilder.Entity("api.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("api.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("api.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ScreeningId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ScreeningId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("api.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A1"
                        });
                });

            modelBuilder.Entity("api.Models.Screening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeStart")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("RoomId");

                    b.ToTable("Screenings");
                });

            modelBuilder.Entity("api.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "Row", "Number")
                        .IsUnique();

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Number = 1,
                            RoomId = 1,
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Number = 2,
                            RoomId = 1,
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Number = 3,
                            RoomId = 1,
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Number = 4,
                            RoomId = 1,
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Number = 5,
                            RoomId = 1,
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Number = 6,
                            RoomId = 1,
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Number = 7,
                            RoomId = 1,
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            Number = 8,
                            RoomId = 1,
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            Number = 9,
                            RoomId = 1,
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            Number = 10,
                            RoomId = 1,
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            Number = 11,
                            RoomId = 1,
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            Number = 12,
                            RoomId = 1,
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            Number = 13,
                            RoomId = 1,
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 14,
                            Number = 14,
                            RoomId = 1,
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 15,
                            Number = 15,
                            RoomId = 1,
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 16,
                            Number = 16,
                            RoomId = 1,
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 17,
                            Number = 17,
                            RoomId = 1,
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 18,
                            Number = 18,
                            RoomId = 1,
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 19,
                            Number = 19,
                            RoomId = 1,
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 20,
                            Number = 20,
                            RoomId = 1,
                            Row = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 21,
                            Number = 1,
                            RoomId = 1,
                            Row = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 22,
                            Number = 2,
                            RoomId = 1,
                            Row = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 23,
                            Number = 3,
                            RoomId = 1,
                            Row = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 24,
                            Number = 4,
                            RoomId = 1,
                            Row = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 25,
                            Number = 5,
                            RoomId = 1,
                            Row = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 26,
                            Number = 6,
                            RoomId = 1,
                            Row = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 27,
                            Number = 7,
                            RoomId = 1,
                            Row = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 28,
                            Number = 8,
                            RoomId = 1,
                            Row = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 29,
                            Number = 9,
                            RoomId = 1,
                            Row = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 30,
                            Number = 10,
                            RoomId = 1,
                            Row = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 31,
                            Number = 11,
                            RoomId = 1,
                            Row = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 32,
                            Number = 12,
                            RoomId = 1,
                            Row = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 33,
                            Number = 13,
                            RoomId = 1,
                            Row = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 34,
                            Number = 14,
                            RoomId = 1,
                            Row = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 35,
                            Number = 15,
                            RoomId = 1,
                            Row = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 36,
                            Number = 16,
                            RoomId = 1,
                            Row = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 37,
                            Number = 17,
                            RoomId = 1,
                            Row = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 38,
                            Number = 18,
                            RoomId = 1,
                            Row = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 39,
                            Number = 19,
                            RoomId = 1,
                            Row = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 40,
                            Number = 20,
                            RoomId = 1,
                            Row = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 41,
                            Number = 1,
                            RoomId = 1,
                            Row = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 42,
                            Number = 2,
                            RoomId = 1,
                            Row = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 43,
                            Number = 3,
                            RoomId = 1,
                            Row = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 44,
                            Number = 4,
                            RoomId = 1,
                            Row = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 45,
                            Number = 5,
                            RoomId = 1,
                            Row = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 46,
                            Number = 6,
                            RoomId = 1,
                            Row = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 47,
                            Number = 7,
                            RoomId = 1,
                            Row = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 48,
                            Number = 8,
                            RoomId = 1,
                            Row = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 49,
                            Number = 9,
                            RoomId = 1,
                            Row = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 50,
                            Number = 10,
                            RoomId = 1,
                            Row = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 51,
                            Number = 11,
                            RoomId = 1,
                            Row = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 52,
                            Number = 12,
                            RoomId = 1,
                            Row = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 53,
                            Number = 13,
                            RoomId = 1,
                            Row = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 54,
                            Number = 14,
                            RoomId = 1,
                            Row = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 55,
                            Number = 15,
                            RoomId = 1,
                            Row = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 56,
                            Number = 16,
                            RoomId = 1,
                            Row = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 57,
                            Number = 17,
                            RoomId = 1,
                            Row = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 58,
                            Number = 18,
                            RoomId = 1,
                            Row = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 59,
                            Number = 19,
                            RoomId = 1,
                            Row = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 60,
                            Number = 20,
                            RoomId = 1,
                            Row = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 61,
                            Number = 1,
                            RoomId = 1,
                            Row = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 62,
                            Number = 2,
                            RoomId = 1,
                            Row = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 63,
                            Number = 3,
                            RoomId = 1,
                            Row = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 64,
                            Number = 4,
                            RoomId = 1,
                            Row = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 65,
                            Number = 5,
                            RoomId = 1,
                            Row = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 66,
                            Number = 6,
                            RoomId = 1,
                            Row = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 67,
                            Number = 7,
                            RoomId = 1,
                            Row = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 68,
                            Number = 8,
                            RoomId = 1,
                            Row = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 69,
                            Number = 9,
                            RoomId = 1,
                            Row = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 70,
                            Number = 10,
                            RoomId = 1,
                            Row = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 71,
                            Number = 11,
                            RoomId = 1,
                            Row = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 72,
                            Number = 12,
                            RoomId = 1,
                            Row = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 73,
                            Number = 13,
                            RoomId = 1,
                            Row = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 74,
                            Number = 14,
                            RoomId = 1,
                            Row = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 75,
                            Number = 15,
                            RoomId = 1,
                            Row = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 76,
                            Number = 16,
                            RoomId = 1,
                            Row = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 77,
                            Number = 17,
                            RoomId = 1,
                            Row = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 78,
                            Number = 18,
                            RoomId = 1,
                            Row = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 79,
                            Number = 19,
                            RoomId = 1,
                            Row = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 80,
                            Number = 20,
                            RoomId = 1,
                            Row = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 81,
                            Number = 1,
                            RoomId = 1,
                            Row = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 82,
                            Number = 2,
                            RoomId = 1,
                            Row = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 83,
                            Number = 3,
                            RoomId = 1,
                            Row = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 84,
                            Number = 4,
                            RoomId = 1,
                            Row = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 85,
                            Number = 5,
                            RoomId = 1,
                            Row = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 86,
                            Number = 6,
                            RoomId = 1,
                            Row = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 87,
                            Number = 7,
                            RoomId = 1,
                            Row = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 88,
                            Number = 8,
                            RoomId = 1,
                            Row = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 89,
                            Number = 9,
                            RoomId = 1,
                            Row = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 90,
                            Number = 10,
                            RoomId = 1,
                            Row = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 91,
                            Number = 11,
                            RoomId = 1,
                            Row = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 92,
                            Number = 12,
                            RoomId = 1,
                            Row = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 93,
                            Number = 13,
                            RoomId = 1,
                            Row = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 94,
                            Number = 14,
                            RoomId = 1,
                            Row = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 95,
                            Number = 15,
                            RoomId = 1,
                            Row = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 96,
                            Number = 16,
                            RoomId = 1,
                            Row = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 97,
                            Number = 17,
                            RoomId = 1,
                            Row = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 98,
                            Number = 18,
                            RoomId = 1,
                            Row = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 99,
                            Number = 19,
                            RoomId = 1,
                            Row = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 100,
                            Number = 20,
                            RoomId = 1,
                            Row = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 101,
                            Number = 1,
                            RoomId = 1,
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 102,
                            Number = 2,
                            RoomId = 1,
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 103,
                            Number = 3,
                            RoomId = 1,
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 104,
                            Number = 4,
                            RoomId = 1,
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 105,
                            Number = 5,
                            RoomId = 1,
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 106,
                            Number = 6,
                            RoomId = 1,
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 107,
                            Number = 7,
                            RoomId = 1,
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 108,
                            Number = 8,
                            RoomId = 1,
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 109,
                            Number = 9,
                            RoomId = 1,
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 110,
                            Number = 10,
                            RoomId = 1,
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 111,
                            Number = 11,
                            RoomId = 1,
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 112,
                            Number = 12,
                            RoomId = 1,
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 113,
                            Number = 13,
                            RoomId = 1,
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 114,
                            Number = 14,
                            RoomId = 1,
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 115,
                            Number = 15,
                            RoomId = 1,
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 116,
                            Number = 16,
                            RoomId = 1,
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 117,
                            Number = 17,
                            RoomId = 1,
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 118,
                            Number = 18,
                            RoomId = 1,
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 119,
                            Number = 19,
                            RoomId = 1,
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 120,
                            Number = 20,
                            RoomId = 1,
                            Row = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 121,
                            Number = 1,
                            RoomId = 1,
                            Row = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 122,
                            Number = 2,
                            RoomId = 1,
                            Row = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 123,
                            Number = 3,
                            RoomId = 1,
                            Row = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 124,
                            Number = 4,
                            RoomId = 1,
                            Row = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 125,
                            Number = 5,
                            RoomId = 1,
                            Row = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 126,
                            Number = 6,
                            RoomId = 1,
                            Row = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 127,
                            Number = 7,
                            RoomId = 1,
                            Row = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 128,
                            Number = 8,
                            RoomId = 1,
                            Row = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 129,
                            Number = 9,
                            RoomId = 1,
                            Row = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 130,
                            Number = 10,
                            RoomId = 1,
                            Row = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 131,
                            Number = 11,
                            RoomId = 1,
                            Row = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 132,
                            Number = 12,
                            RoomId = 1,
                            Row = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 133,
                            Number = 13,
                            RoomId = 1,
                            Row = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 134,
                            Number = 14,
                            RoomId = 1,
                            Row = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 135,
                            Number = 15,
                            RoomId = 1,
                            Row = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 136,
                            Number = 16,
                            RoomId = 1,
                            Row = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 137,
                            Number = 17,
                            RoomId = 1,
                            Row = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 138,
                            Number = 18,
                            RoomId = 1,
                            Row = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 139,
                            Number = 19,
                            RoomId = 1,
                            Row = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 140,
                            Number = 20,
                            RoomId = 1,
                            Row = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 141,
                            Number = 1,
                            RoomId = 1,
                            Row = 8,
                            Type = 0
                        },
                        new
                        {
                            Id = 142,
                            Number = 2,
                            RoomId = 1,
                            Row = 8,
                            Type = 0
                        },
                        new
                        {
                            Id = 143,
                            Number = 3,
                            RoomId = 1,
                            Row = 8,
                            Type = 0
                        },
                        new
                        {
                            Id = 144,
                            Number = 4,
                            RoomId = 1,
                            Row = 8,
                            Type = 0
                        },
                        new
                        {
                            Id = 145,
                            Number = 5,
                            RoomId = 1,
                            Row = 8,
                            Type = 0
                        },
                        new
                        {
                            Id = 146,
                            Number = 6,
                            RoomId = 1,
                            Row = 8,
                            Type = 0
                        },
                        new
                        {
                            Id = 147,
                            Number = 7,
                            RoomId = 1,
                            Row = 8,
                            Type = 0
                        },
                        new
                        {
                            Id = 148,
                            Number = 8,
                            RoomId = 1,
                            Row = 8,
                            Type = 0
                        },
                        new
                        {
                            Id = 149,
                            Number = 9,
                            RoomId = 1,
                            Row = 8,
                            Type = 0
                        },
                        new
                        {
                            Id = 150,
                            Number = 10,
                            RoomId = 1,
                            Row = 8,
                            Type = 0
                        },
                        new
                        {
                            Id = 151,
                            Number = 11,
                            RoomId = 1,
                            Row = 8,
                            Type = 0
                        },
                        new
                        {
                            Id = 152,
                            Number = 12,
                            RoomId = 1,
                            Row = 8,
                            Type = 0
                        },
                        new
                        {
                            Id = 153,
                            Number = 13,
                            RoomId = 1,
                            Row = 8,
                            Type = 0
                        },
                        new
                        {
                            Id = 154,
                            Number = 14,
                            RoomId = 1,
                            Row = 8,
                            Type = 0
                        },
                        new
                        {
                            Id = 155,
                            Number = 15,
                            RoomId = 1,
                            Row = 8,
                            Type = 0
                        },
                        new
                        {
                            Id = 156,
                            Number = 16,
                            RoomId = 1,
                            Row = 8,
                            Type = 0
                        },
                        new
                        {
                            Id = 157,
                            Number = 17,
                            RoomId = 1,
                            Row = 8,
                            Type = 0
                        },
                        new
                        {
                            Id = 158,
                            Number = 18,
                            RoomId = 1,
                            Row = 8,
                            Type = 0
                        },
                        new
                        {
                            Id = 159,
                            Number = 19,
                            RoomId = 1,
                            Row = 8,
                            Type = 0
                        },
                        new
                        {
                            Id = 160,
                            Number = 20,
                            RoomId = 1,
                            Row = 8,
                            Type = 0
                        },
                        new
                        {
                            Id = 161,
                            Number = 1,
                            RoomId = 1,
                            Row = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 162,
                            Number = 2,
                            RoomId = 1,
                            Row = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 163,
                            Number = 3,
                            RoomId = 1,
                            Row = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 164,
                            Number = 4,
                            RoomId = 1,
                            Row = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 165,
                            Number = 5,
                            RoomId = 1,
                            Row = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 166,
                            Number = 6,
                            RoomId = 1,
                            Row = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 167,
                            Number = 7,
                            RoomId = 1,
                            Row = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 168,
                            Number = 8,
                            RoomId = 1,
                            Row = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 169,
                            Number = 9,
                            RoomId = 1,
                            Row = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 170,
                            Number = 10,
                            RoomId = 1,
                            Row = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 171,
                            Number = 11,
                            RoomId = 1,
                            Row = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 172,
                            Number = 12,
                            RoomId = 1,
                            Row = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 173,
                            Number = 13,
                            RoomId = 1,
                            Row = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 174,
                            Number = 14,
                            RoomId = 1,
                            Row = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 175,
                            Number = 15,
                            RoomId = 1,
                            Row = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 176,
                            Number = 16,
                            RoomId = 1,
                            Row = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 177,
                            Number = 17,
                            RoomId = 1,
                            Row = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 178,
                            Number = 18,
                            RoomId = 1,
                            Row = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 179,
                            Number = 19,
                            RoomId = 1,
                            Row = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 180,
                            Number = 20,
                            RoomId = 1,
                            Row = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 181,
                            Number = 1,
                            RoomId = 1,
                            Row = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = 182,
                            Number = 2,
                            RoomId = 1,
                            Row = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = 183,
                            Number = 3,
                            RoomId = 1,
                            Row = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = 184,
                            Number = 4,
                            RoomId = 1,
                            Row = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = 185,
                            Number = 5,
                            RoomId = 1,
                            Row = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = 186,
                            Number = 6,
                            RoomId = 1,
                            Row = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = 187,
                            Number = 7,
                            RoomId = 1,
                            Row = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = 188,
                            Number = 8,
                            RoomId = 1,
                            Row = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = 189,
                            Number = 9,
                            RoomId = 1,
                            Row = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = 190,
                            Number = 10,
                            RoomId = 1,
                            Row = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = 191,
                            Number = 11,
                            RoomId = 1,
                            Row = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = 192,
                            Number = 12,
                            RoomId = 1,
                            Row = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = 193,
                            Number = 13,
                            RoomId = 1,
                            Row = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = 194,
                            Number = 14,
                            RoomId = 1,
                            Row = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = 195,
                            Number = 15,
                            RoomId = 1,
                            Row = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = 196,
                            Number = 16,
                            RoomId = 1,
                            Row = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = 197,
                            Number = 17,
                            RoomId = 1,
                            Row = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = 198,
                            Number = 18,
                            RoomId = 1,
                            Row = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = 199,
                            Number = 19,
                            RoomId = 1,
                            Row = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = 200,
                            Number = 20,
                            RoomId = 1,
                            Row = 10,
                            Type = 0
                        });
                });

            modelBuilder.Entity("api.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.HasOne("api.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReservationSeat", b =>
                {
                    b.HasOne("api.Models.Reservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Seat", null)
                        .WithMany()
                        .HasForeignKey("SeatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.Reservation", b =>
                {
                    b.HasOne("api.Models.Screening", "Screening")
                        .WithMany("Reservations")
                        .HasForeignKey("ScreeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Screening");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Models.Screening", b =>
                {
                    b.HasOne("api.Models.Movie", "Movie")
                        .WithMany("Screenings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("api.Models.Seat", b =>
                {
                    b.HasOne("api.Models.Room", "Room")
                        .WithMany("Seats")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("api.Models.Movie", b =>
                {
                    b.Navigation("Screenings");
                });

            modelBuilder.Entity("api.Models.Room", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("api.Models.Screening", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("api.Models.User", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
